In [1]:
from MPA import MPA
import numpy as np

In [2]:
def fn(x):
    return x**2 + 2

In [3]:
mpa= MPA(15, 10, [-10], [10], 1, fn)

In [4]:
mpa.initialize()

In [5]:
mpa.Prey.shape

(15, 2)

In [6]:
mpa.levy(3, 4, 1)

array([[-0.9672313 ,  0.03555334, -3.92379854, -2.5218846 ],
       [ 0.25581812,  1.18690186,  0.36218874,  0.41710057],
       [ 4.19589542, -2.38935263, -0.59716749, -0.2041437 ]])

In [7]:
mpa.run()

[[  8.60681293]
 [ 79.88612966]
 [ 55.49388489]
 [ 10.5706135 ]
 [  2.55327844]
 [ 64.734972  ]
 [ 25.954053  ]
 [  3.61257199]
 [ 97.80536996]
 [ 21.51350977]
 [  2.25598051]
 [ 66.211351  ]
 [100.40320847]
 [ 42.10334383]
 [ 52.83331587]]
[[  8.60681293]
 [ 79.88612966]
 [ 55.49388489]
 [ 10.5706135 ]
 [  2.55327844]
 [ 64.734972  ]
 [ 25.954053  ]
 [  3.61257199]
 [ 97.80536996]
 [ 21.51350977]
 [  2.25598051]
 [ 66.211351  ]
 [100.40320847]
 [ 42.10334383]
 [ 52.83331587]]
[[  5.29558679]
 [ 11.33471607]
 [ 23.89072589]
 [ 23.67901499]
 [  2.08837642]
 [  4.86709813]
 [ 30.45251211]
 [  2.2969885 ]
 [102.        ]
 [  3.06137109]
 [  2.05984303]
 [ 26.13784614]
 [ 53.36915648]
 [  3.03244262]
 [ 78.66676429]]
[[  5.29558679]
 [ 11.33471607]
 [ 23.89072589]
 [ 23.67901499]
 [  2.08837642]
 [  4.86709813]
 [ 30.45251211]
 [  2.2969885 ]
 [102.        ]
 [  3.06137109]
 [  2.05984303]
 [ 26.13784614]
 [ 53.36915648]
 [  3.03244262]
 [ 78.66676429]]
[[ 2.09835774]
 [17.4517366 ]
 [18.4

In [8]:
mpa.convergence_curve

[array([2.25598051]),
 array([2.05180433]),
 array([2.03356905]),
 array([2.00816103]),
 array([2.00026832]),
 array([2.00013758]),
 array([2.00007883]),
 array([2.00000824]),
 array([2.00000005]),
 array([2.00000004])]

In [9]:
mpa.fitness

array([[2.00000005],
       [2.00000005],
       [2.00000007],
       [2.00000005],
       [2.00000005],
       [2.00000004],
       [2.00000021],
       [2.00000005],
       [2.00000005],
       [2.00000011],
       [2.00000007],
       [2.00000005],
       [2.00000005],
       [2.00000005],
       [2.00000005]])